import React, { useState, useEffect } from 'react';
import { 
  Plus, 
  Trash2, 
  Users, 
  Trophy, 
  UserCheck, 
  UserX, 
  Clock, 
  MapPin, 
  School, 
  Download, 
  Printer, 
  CheckCircle2, 
  Sparkles, 
  FileSpreadsheet,
  AlertCircle,
  Phone,
  BookOpen,
  Info
} from 'lucide-react';
import { 
  HomeroomMeetingMinutesData, 
  TalentAchievementItem, 
  ClassCadreItem, 
  AbsentStudentItem, 
  User 
} from '../../types';
import { 
  exportHomeroomReportToWord, 
  exportAbsentStudentsToExcel, 
  generateHomeroomMinutesText 
} from '../../utils/homeroomReportExporter';

interface HomeroomMeetingMinutesFormProps {
  currentUser: User;
  initialData?: HomeroomMeetingMinutesData;
  onChange: (data: HomeroomMeetingMinutesData, generatedText: string) => void;
  onAutoGeneratedText?: (text: string) => void;
}

// Danh sách cuộc thi mặc định theo mẫu yêu cầu
const DEFAULT_TALENTS: Omit<TalentAchievementItem, 'id' | 'tt'>[] = [
  { competition: 'Văn nghệ vòng tỉnh, vòng xã', prize: '', studentName: '' },
  { competition: 'Hội khỏe phù đổng', prize: '', studentName: '' },
  { competition: 'Giải thể thao học sinh tỉnh Đồng Tháp', prize: '', studentName: '' },
  { competition: 'Sáng tạo thanh thiếu niên nhi đồng', prize: '', studentName: '' },
  { competition: 'Khoa học kỹ thuật', prize: '', studentName: '' },
  { competition: 'Vẽ tranh', prize: '', studentName: '' },
  { competition: 'Phong trào khác', prize: '', studentName: '', note: '' },
  { competition: 'Thành tích khác', prize: '', studentName: '', note: '' },
];

// Danh sách các chức danh ban cán sự mặc định
const DEFAULT_CADRES: Omit<ClassCadreItem, 'id' | 'tt'>[] = [
  { role: 'Lớp trưởng', studentName: '', academicPerf: 'Tốt', conductPerf: 'Tốt', phone: '' },
  { role: 'Lớp phó học tập', studentName: '', academicPerf: 'Tốt', conductPerf: 'Tốt', phone: '' },
  { role: 'Lớp phó lao động / phong trào', studentName: '', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '' },
  { role: 'Lớp phó trật tự / kỷ luật', studentName: '', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '' },
  { role: 'Bí thư Chi đoàn / Chi đội', studentName: '', academicPerf: 'Tốt', conductPerf: 'Tốt', phone: '' },
  { role: 'Phó Bí thư', studentName: '', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '' },
  { role: 'Tổ trưởng Tổ 1', studentName: '', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '' },
  { role: 'Tổ trưởng Tổ 2', studentName: '', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '' },
  { role: 'Tổ trưởng Tổ 3', studentName: '', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '' },
  { role: 'Tổ trưởng Tổ 4', studentName: '', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '' },
];

export const HomeroomMeetingMinutesForm: React.FC<HomeroomMeetingMinutesFormProps> = ({
  currentUser,
  initialData,
  onChange
}) => {
  // Active sub-tab
  const [activeSection, setActiveSection] = useState<'info' | 'talents' | 'cadres' | 'absent' | 'preview'>('info');

  // Form State
  const [formData, setFormData] = useState<HomeroomMeetingMinutesData>(() => {
    if (initialData) return initialData;

    // Build default initial form data
    const total = currentUser.homeroomStudentCount || 35;
    const female = Math.floor(total / 2);
    const male = total - female;

    return {
      academicYear: '2026 – 2027',
      timeHour: '07',
      timeMinute: '30',
      meetingDate: '28',
      meetingMonth: '8',
      meetingYear: '2026',
      roomNumber: currentUser.homeroomClass ? `Phòng học lớp ${currentUser.homeroomClass}` : 'Phòng 01',
      teacherName: currentUser.name,
      className: currentUser.homeroomClass || '',
      totalStudents: total,
      maleStudents: male,
      femaleStudents: female,
      absentCount: 0,
      talents: DEFAULT_TALENTS.map((t, idx) => ({ ...t, id: `talent-${idx + 1}`, tt: idx + 1 })),
      cadres: DEFAULT_CADRES.map((c, idx) => ({ ...c, id: `cadre-${idx + 1}`, tt: idx + 1 })),
      absentStudents: [],
      additionalNotes: ''
    };
  });

  // Automatically update absentCount when absentStudents array changes
  useEffect(() => {
    const calculatedAbsent = formData.absentStudents.length;
    if (calculatedAbsent !== formData.absentCount) {
      setFormData(prev => ({ ...prev, absentCount: calculatedAbsent }));
    }
  }, [formData.absentStudents]);

  // Sync back to parent whenever formData changes
  useEffect(() => {
    const text = generateHomeroomMinutesText(formData);
    onChange(formData, text);
  }, [formData, onChange]);

  // Field change handler
  const handleFieldChange = (field: keyof HomeroomMeetingMinutesData, value: any) => {
    setFormData(prev => {
      const updated = { ...prev, [field]: value };
      // If male/female changes, update total if needed
      if (field === 'maleStudents' || field === 'femaleStudents') {
        const m = field === 'maleStudents' ? Number(value) : Number(prev.maleStudents);
        const f = field === 'femaleStudents' ? Number(value) : Number(prev.femaleStudents);
        updated.totalStudents = m + f;
      }
      return updated;
    });
  };

  // Talent Handlers
  const handleTalentChange = (index: number, field: keyof TalentAchievementItem, value: string) => {
    setFormData(prev => {
      const newTalents = [...prev.talents];
      newTalents[index] = { ...newTalents[index], [field]: value };
      return { ...prev, talents: newTalents };
    });
  };

  const handleAddTalentRow = () => {
    setFormData(prev => ({
      ...prev,
      talents: [
        ...prev.talents,
        {
          id: `talent-${Date.now()}`,
          tt: prev.talents.length + 1,
          competition: 'Phong trào / Cuộc thi khác...',
          prize: '',
          studentName: ''
        }
      ]
    }));
  };

  const handleRemoveTalentRow = (index: number) => {
    setFormData(prev => ({
      ...prev,
      talents: prev.talents.filter((_, idx) => idx !== index).map((item, idx) => ({ ...item, tt: idx + 1 }))
    }));
  };

  // Cadre Handlers
  const handleCadreChange = (index: number, field: keyof ClassCadreItem, value: string) => {
    setFormData(prev => {
      const newCadres = [...prev.cadres];
      newCadres[index] = { ...newCadres[index], [field]: value };
      return { ...prev, cadres: newCadres };
    });
  };

  const handleAddCadreRow = () => {
    setFormData(prev => ({
      ...prev,
      cadres: [
        ...prev.cadres,
        {
          id: `cadre-${Date.now()}`,
          tt: prev.cadres.length + 1,
          role: 'Tổ phó / Cán sự bộ môn...',
          studentName: '',
          academicPerf: 'Khá',
          conductPerf: 'Tốt',
          phone: ''
        }
      ]
    }));
  };

  const handleRemoveCadreRow = (index: number) => {
    setFormData(prev => ({
      ...prev,
      cadres: prev.cadres.filter((_, idx) => idx !== index).map((item, idx) => ({ ...item, tt: idx + 1 }))
    }));
  };

  // Absent Student Handlers
  const handleAbsentChange = (index: number, field: keyof AbsentStudentItem, value: string) => {
    setFormData(prev => {
      const newAbsents = [...prev.absentStudents];
      newAbsents[index] = { ...newAbsents[index], [field]: value };
      return { ...prev, absentStudents: newAbsents };
    });
  };

  const handleAddAbsentRow = () => {
    setFormData(prev => ({
      ...prev,
      absentStudents: [
        ...prev.absentStudents,
        {
          id: `absent-${Date.now()}`,
          tt: prev.absentStudents.length + 1,
          studentName: '',
          previousClass: prev.className ? `Lớp cũ` : '',
          currentAddress: '',
          studentPhone: '',
          parentPhone: '',
          reason: 'Chưa liên lạc được / Đi làm xa...'
        }
      ]
    }));
  };

  const handleRemoveAbsentRow = (index: number) => {
    setFormData(prev => ({
      ...prev,
      absentStudents: prev.absentStudents.filter((_, idx) => idx !== index).map((item, idx) => ({ ...item, tt: idx + 1 }))
    }));
  };

  const handleClearAbsents = () => {
    if (confirm('Xác nhận lớp tập trung đầy đủ 100% (không có học sinh vắng)?')) {
      setFormData(prev => ({ ...prev, absentStudents: [], absentCount: 0 }));
    }
  };

  // Fill quick demo sample data for fast testing
  const handleFillDemoData = () => {
    setFormData(prev => ({
      ...prev,
      talents: [
        { id: 't1', tt: 1, competition: 'Văn nghệ vòng tỉnh, vòng xã', prize: 'Giải Nhất Huyện', studentName: 'Nguyễn Thị Mai Anh' },
        { id: 't2', tt: 2, competition: 'Hội khỏe phù đổng', prize: 'Huy chương Bạc Điền kinh', studentName: 'Trần Văn Nam' },
        { id: 't3', tt: 3, competition: 'Giải thể thao học sinh tỉnh Đồng Tháp', prize: 'Giải Ba Cầu lông', studentName: 'Lê Hoàng Phúc' },
        { id: 't4', tt: 4, competition: 'Sáng tạo thanh thiếu niên nhi đồng', prize: 'Giải Khuyến khích', studentName: 'Phạm Minh Tuấn' },
        { id: 't5', tt: 5, competition: 'Khoa học kỹ thuật', prize: '', studentName: 'Chưa có' },
        { id: 't6', tt: 6, competition: 'Vẽ tranh', prize: 'Giải Nhì cấp Trường', studentName: 'Đặng Ngọc Hân' },
        { id: 't7', tt: 7, competition: 'Phong trào Chỉ huy Đội / Đoàn giỏi', prize: 'Bằng khen', studentName: 'Võ Thị Thanh Thảo' },
        { id: 't8', tt: 8, competition: 'Thành tích khác: Học sinh 3 tốt', prize: 'Cấp Huyện', studentName: 'Nguyễn Hữu Tài' },
      ],
      cadres: [
        { id: 'c1', tt: 1, role: 'Lớp trưởng', studentName: 'Nguyễn Văn An', academicPerf: 'Tốt', conductPerf: 'Tốt', phone: '0912345678' },
        { id: 'c2', tt: 2, role: 'Lớp phó học tập', studentName: 'Lê Thị Bích', academicPerf: 'Tốt', conductPerf: 'Tốt', phone: '0987654321' },
        { id: 'c3', tt: 3, role: 'Lớp phó lao động / phong trào', studentName: 'Trần Văn Cường', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '0933112233' },
        { id: 'c4', tt: 4, role: 'Lớp phó trật tự / kỷ luật', studentName: 'Phạm Thị Diễm', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '0944556677' },
        { id: 'c5', tt: 5, role: 'Bí thư Chi đoàn / Chi đội', studentName: 'Hoàng Minh Đức', academicPerf: 'Tốt', conductPerf: 'Tốt', phone: '0966778899' },
        { id: 'c6', tt: 6, role: 'Phó Bí thư', studentName: 'Vũ Thị Hòa', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '0977889900' },
        { id: 'c7', tt: 7, role: 'Tổ trưởng Tổ 1', studentName: 'Đỗ Quốc Hưng', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '0911223344' },
        { id: 'c8', tt: 8, role: 'Tổ trưởng Tổ 2', studentName: 'Ngô Thanh Lan', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '0922334455' },
        { id: 'c9', tt: 9, role: 'Tổ trưởng Tổ 3', studentName: 'Bùi Thị Mai', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '0933445566' },
        { id: 'c10', tt: 10, role: 'Tổ trưởng Tổ 4', studentName: 'Lý Quốc Nam', academicPerf: 'Khá', conductPerf: 'Tốt', phone: '0944556677' },
      ],
      absentStudents: [
        {
          id: 'a1',
          tt: 1,
          studentName: 'Trần Văn Đạt',
          previousClass: '11CB2',
          currentAddress: 'Ấp 2, Xã Đốc Binh Kiều (Gần cầu Kênh Ranh)',
          studentPhone: '0981112233',
          parentPhone: '0973334455',
          reason: 'Gia đình đi làm ăn xa tại Bình Dương, dự kiến nhập học vào ngày 05/09'
        },
        {
          id: 'a2',
          tt: 2,
          studentName: 'Nguyễn Thị Hồng',
          previousClass: '11CB1',
          currentAddress: 'Ấp 4, Xã Đốc Binh Kiều (Gần ngã ba chợ)',
          studentPhone: '',
          parentPhone: '0918889900',
          reason: 'Bị sốt xuất huyết, gia đình có xin phép hoãn tập trung 3 ngày'
        }
      ]
    }));
  };

  return (
    <div className="space-y-4">
      {/* Top Banner Notice & Actions */}
      <div className="p-3.5 bg-gradient-to-r from-emerald-50 via-teal-50 to-emerald-50 border border-emerald-200 rounded-2xl flex flex-wrap items-center justify-between gap-3 shadow-2xs">
        <div className="flex items-center gap-2.5">
          <div className="w-9 h-9 rounded-xl bg-emerald-600 text-white flex items-center justify-center font-bold text-sm shrink-0 shadow-sm">
            <School className="w-5 h-5" />
          </div>
          <div>
            <div className="text-xs sm:text-sm font-bold text-emerald-950 flex items-center gap-2">
              <span>Mẫu Biên Bản Tập Trung Đầu Năm Học {formData.academicYear}</span>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-extrabold bg-emerald-200 text-emerald-900">
                Lớp {formData.className || '...'}
              </span>
            </div>
            <p className="text-[11px] text-emerald-800 font-medium">
              Kèm bảng theo dõi Năng khiếu, Phân công Ban cán sự và Danh sách học sinh vắng.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-1.5 ml-auto">
          <button
            type="button"
            onClick={handleFillDemoData}
            className="px-2.5 py-1.5 rounded-xl bg-white hover:bg-emerald-100 border border-emerald-300 text-emerald-800 text-xs font-bold transition flex items-center gap-1 cursor-pointer shadow-2xs"
            title="Điền dữ liệu mẫu minh họa nhanh"
          >
            <Sparkles className="w-3.5 h-3.5 text-emerald-600" />
            <span className="hidden sm:inline">Điền mẫu</span>
          </button>

          <button
            type="button"
            onClick={() => exportHomeroomReportToWord(formData)}
            className="px-2.5 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold transition flex items-center gap-1 cursor-pointer shadow-2xs"
            title="Xuất file Word (.doc) đúng chuẩn hành chính"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Tải Word (.doc)</span>
          </button>
        </div>
      </div>

      {/* Navigation Sub-Tabs */}
      <div className="flex border-b border-slate-200 overflow-x-auto gap-1 text-xs">
        <button
          type="button"
          onClick={() => setActiveSection('info')}
          className={`px-3 py-2 font-bold border-b-2 whitespace-nowrap transition cursor-pointer flex items-center gap-1.5 ${
            activeSection === 'info'
              ? 'border-emerald-600 text-emerald-700 bg-emerald-50/50'
              : 'border-transparent text-slate-600 hover:text-slate-900'
          }`}
        >
          <Clock className="w-4 h-4 text-emerald-600" />
          <span>I. Thông Tin Buổi Tập Trung</span>
        </button>

        <button
          type="button"
          onClick={() => setActiveSection('talents')}
          className={`px-3 py-2 font-bold border-b-2 whitespace-nowrap transition cursor-pointer flex items-center gap-1.5 ${
            activeSection === 'talents'
              ? 'border-emerald-600 text-emerald-700 bg-emerald-50/50'
              : 'border-transparent text-slate-600 hover:text-slate-900'
          }`}
        >
          <Trophy className="w-4 h-4 text-amber-600" />
          <span>II. Năng Khiếu & Thành Tích ({formData.talents.filter(t => t.studentName).length})</span>
        </button>

        <button
          type="button"
          onClick={() => setActiveSection('cadres')}
          className={`px-3 py-2 font-bold border-b-2 whitespace-nowrap transition cursor-pointer flex items-center gap-1.5 ${
            activeSection === 'cadres'
              ? 'border-emerald-600 text-emerald-700 bg-emerald-50/50'
              : 'border-transparent text-slate-600 hover:text-slate-900'
          }`}
        >
          <UserCheck className="w-4 h-4 text-blue-600" />
          <span>III. Ban Cán Sự Lớp ({formData.cadres.filter(c => c.studentName).length})</span>
        </button>

        <button
          type="button"
          onClick={() => setActiveSection('absent')}
          className={`px-3 py-2 font-bold border-b-2 whitespace-nowrap transition cursor-pointer flex items-center gap-1.5 ${
            activeSection === 'absent'
              ? 'border-rose-600 text-rose-700 bg-rose-50/50'
              : 'border-transparent text-slate-600 hover:text-slate-900'
          }`}
        >
          <UserX className="w-4 h-4 text-rose-600" />
          <span>IV. DS Học Sinh Vắng ({formData.absentStudents.length})</span>
          {formData.absentStudents.length > 0 && (
            <span className="px-1.5 py-0.2 rounded-full bg-rose-600 text-white text-[10px] font-bold">
              {formData.absentStudents.length}
            </span>
          )}
        </button>

        <button
          type="button"
          onClick={() => setActiveSection('preview')}
          className={`px-3 py-2 font-bold border-b-2 whitespace-nowrap transition cursor-pointer flex items-center gap-1.5 ml-auto ${
            activeSection === 'preview'
              ? 'border-emerald-600 text-emerald-700 bg-emerald-50/50'
              : 'border-transparent text-slate-600 hover:text-slate-900'
          }`}
        >
          <BookOpen className="w-4 h-4 text-slate-600" />
          <span>Xem Trước Biên Bản</span>
        </button>
      </div>

      {/* SECTION I: THÔNG TIN BUỔI TẬP TRUNG */}
      {activeSection === 'info' && (
        <div className="p-4 bg-white border border-slate-200 rounded-2xl space-y-4 shadow-2xs">
          <div className="border-b border-slate-100 pb-2 flex items-center justify-between">
            <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider flex items-center gap-1.5">
              <Clock className="w-4 h-4 text-emerald-600" />
              <span>Thời Gian & Địa Điểm Tập Trung</span>
            </h4>
            <span className="text-[11px] text-slate-400">Năm học {formData.academicYear}</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3">
            <div>
              <label className="block text-[11px] font-bold text-slate-700 mb-1">
                Thời gian (Giờ : Phút)
              </label>
              <div className="flex items-center gap-1.5">
                <input
                  type="text"
                  value={formData.timeHour}
                  onChange={(e) => handleFieldChange('timeHour', e.target.value)}
                  placeholder="07"
                  className="w-1/2 text-center text-xs p-2 rounded-xl bg-slate-50 border border-slate-300 focus:bg-white focus:border-emerald-600 focus:outline-hidden font-bold"
                />
                <span className="font-bold text-slate-400">:</span>
                <input
                  type="text"
                  value={formData.timeMinute}
                  onChange={(e) => handleFieldChange('timeMinute', e.target.value)}
                  placeholder="30"
                  className="w-1/2 text-center text-xs p-2 rounded-xl bg-slate-50 border border-slate-300 focus:bg-white focus:border-emerald-600 focus:outline-hidden font-bold"
                />
              </div>
            </div>

            <div>
              <label className="block text-[11px] font-bold text-slate-700 mb-1">
                Ngày tập trung (Ngày/Tháng/Năm)
              </label>
              <div className="flex items-center gap-1">
                <input
                  type="text"
                  value={formData.meetingDate}
                  onChange={(e) => handleFieldChange('meetingDate', e.target.value)}
                  placeholder="28"
                  className="w-1/3 text-center text-xs p-2 rounded-xl bg-slate-50 border border-slate-300 focus:bg-white focus:border-emerald-600 focus:outline-hidden"
                />
                <span className="text-slate-400">/</span>
                <input
                  type="text"
                  value={formData.meetingMonth}
                  onChange={(e) => handleFieldChange('meetingMonth', e.target.value)}
                  placeholder="8"
                  className="w-1/3 text-center text-xs p-2 rounded-xl bg-slate-50 border border-slate-300 focus:bg-white focus:border-emerald-600 focus:outline-hidden"
                />
                <span className="text-slate-400">/</span>
                <input
                  type="text"
                  value={formData.meetingYear}
                  onChange={(e) => handleFieldChange('meetingYear', e.target.value)}
                  placeholder="2026"
                  className="w-1/3 text-center text-xs p-2 rounded-xl bg-slate-50 border border-slate-300 focus:bg-white focus:border-emerald-600 focus:outline-hidden"
                />
              </div>
            </div>

            <div className="sm:col-span-2">
              <label className="block text-[11px] font-bold text-slate-700 mb-1">
                Địa điểm (Phòng học / Cơ sở)
              </label>
              <input
                type="text"
                value={formData.roomNumber}
                onChange={(e) => handleFieldChange('roomNumber', e.target.value)}
                placeholder="Phòng số 12 trường THCS-THPT Đốc Binh Kiều"
                className="w-full text-xs p-2 rounded-xl bg-slate-50 border border-slate-300 focus:bg-white focus:border-emerald-600 focus:outline-hidden"
              />
            </div>
          </div>

          <div className="border-t border-slate-100 pt-3">
            <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider mb-2 flex items-center gap-1.5">
              <Users className="w-4 h-4 text-emerald-600" />
              <span>Thông Tin Lớp & Sĩ Số</span>
            </h4>

            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-5 gap-3">
              <div>
                <label className="block text-[11px] font-bold text-slate-700 mb-1">
                  Họ tên GVCN
                </label>
                <input
                  type="text"
                  value={formData.teacherName}
                  onChange={(e) => handleFieldChange('teacherName', e.target.value)}
                  className="w-full text-xs p-2 rounded-xl bg-slate-100 border border-slate-300 font-bold text-slate-800"
                />
              </div>

              <div>
                <label className="block text-[11px] font-bold text-slate-700 mb-1">
                  Lớp chủ nhiệm
                </label>
                <input
                  type="text"
                  value={formData.className}
                  onChange={(e) => handleFieldChange('className', e.target.value)}
                  placeholder="12CB1, 6A1..."
                  className="w-full text-xs p-2 rounded-xl bg-slate-50 border border-slate-300 focus:bg-white focus:border-emerald-600 focus:outline-hidden font-bold text-emerald-800"
                />
              </div>

              <div>
                <label className="block text-[11px] font-bold text-slate-700 mb-1">
                  Tổng số học sinh
                </label>
                <input
                  type="number"
                  value={formData.totalStudents}
                  onChange={(e) => handleFieldChange('totalStudents', Number(e.target.value))}
                  className="w-full text-xs p-2 rounded-xl bg-emerald-50 border border-emerald-300 focus:bg-white focus:border-emerald-600 font-bold text-emerald-900"
                />
              </div>

              <div>
                <label className="block text-[11px] font-bold text-slate-700 mb-1">
                  Trong đó: Nam / Nữ
                </label>
                <div className="flex items-center gap-1.5">
                  <input
                    type="number"
                    value={formData.maleStudents}
                    onChange={(e) => handleFieldChange('maleStudents', Number(e.target.value))}
                    placeholder="Nam"
                    title="Số học sinh nam"
                    className="w-1/2 text-xs p-2 rounded-xl bg-slate-50 border border-slate-300 text-center"
                  />
                  <span className="text-slate-400">/</span>
                  <input
                    type="number"
                    value={formData.femaleStudents}
                    onChange={(e) => handleFieldChange('femaleStudents', Number(e.target.value))}
                    placeholder="Nữ"
                    title="Số học sinh nữ"
                    className="w-1/2 text-xs p-2 rounded-xl bg-slate-50 border border-slate-300 text-center"
                  />
                </div>
              </div>

              <div>
                <label className="block text-[11px] font-bold text-slate-700 mb-1">
                  Số HS Vắng
                </label>
                <div className="flex items-center gap-1.5">
                  <input
                    type="number"
                    value={formData.absentCount}
                    readOnly
                    className="w-full text-xs p-2 rounded-xl bg-rose-50 border border-rose-300 font-extrabold text-rose-800 text-center"
                  />
                </div>
              </div>
            </div>
          </div>

          <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl text-xs text-amber-900 flex items-start gap-2">
            <Info className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
            <div>
              <strong>Lưu ý quan trọng từ Ban Giám Hiệu:</strong> GVCN gửi danh sách học sinh vắng <u>SAU KHI KẾT THÚC BUỔI TẬP TRUNG HỌC SINH ĐẦU NĂM</u> để nhà trường và địa phương phối hợp vận động các em ra lớp kịp thời.
            </div>
          </div>
        </div>
      )}

      {/* SECTION II: NĂNG KHIẾU & THÀNH TÍCH */}
      {activeSection === 'talents' && (
        <div className="p-4 bg-white border border-slate-200 rounded-2xl space-y-3 shadow-2xs">
          <div className="flex items-center justify-between border-b border-slate-100 pb-2">
            <div>
              <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider flex items-center gap-1.5">
                <Trophy className="w-4 h-4 text-amber-600" />
                <span>Tìm Hiểu Về Năng Khiếu, Thành Tích Của Học Sinh</span>
              </h4>
              <p className="text-[11px] text-slate-500">
                Ghi nhận các cuộc thi, hội thao, giải thưởng để xây dựng nguồn phát triển phong trào của lớp và trường.
              </p>
            </div>
            <button
              type="button"
              onClick={handleAddTalentRow}
              className="px-2.5 py-1 rounded-lg bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border border-emerald-200 text-xs font-bold transition flex items-center gap-1 cursor-pointer"
            >
              <Plus className="w-3.5 h-3.5" />
              <span>Thêm cuộc thi</span>
            </button>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left border-collapse">
              <thead>
                <tr className="bg-slate-100 text-slate-700 font-bold border-b border-slate-200">
                  <th className="p-2.5 w-12 text-center">TT</th>
                  <th className="p-2.5 w-1/3">Cuộc thi / Phong trào</th>
                  <th className="p-2.5 w-1/4">Đạt giải (Nhất, Nhì, Ba, Cấp...)</th>
                  <th className="p-2.5">Họ tên học sinh đạt giải</th>
                  <th className="p-2.5 w-10 text-center">Xóa</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {formData.talents.map((talent, idx) => (
                  <tr key={talent.id} className="hover:bg-slate-50/80 transition">
                    <td className="p-2 text-center font-bold text-slate-400">
                      {idx + 1}
                    </td>
                    <td className="p-2">
                      <input
                        type="text"
                        value={talent.competition}
                        onChange={(e) => handleTalentChange(idx, 'competition', e.target.value)}
                        placeholder="Tên cuộc thi / phong trào"
                        className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white focus:border-emerald-600 focus:outline-hidden font-medium"
                      />
                    </td>
                    <td className="p-2">
                      <input
                        type="text"
                        value={talent.prize}
                        onChange={(e) => handleTalentChange(idx, 'prize', e.target.value)}
                        placeholder="Giải Nhất, Nhì, Ba, KK..."
                        className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white focus:border-emerald-600 focus:outline-hidden"
                      />
                    </td>
                    <td className="p-2">
                      <input
                        type="text"
                        value={talent.studentName}
                        onChange={(e) => handleTalentChange(idx, 'studentName', e.target.value)}
                        placeholder="Họ và tên học sinh (nếu có)"
                        className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white focus:border-emerald-600 focus:outline-hidden font-medium text-slate-800"
                      />
                    </td>
                    <td className="p-2 text-center">
                      <button
                        type="button"
                        onClick={() => handleRemoveTalentRow(idx)}
                        className="p-1 rounded text-slate-300 hover:text-rose-600 hover:bg-rose-50 transition cursor-pointer"
                        title="Xóa dòng này"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* SECTION III: BAN CÁN SỰ LỚP */}
      {activeSection === 'cadres' && (
        <div className="p-4 bg-white border border-slate-200 rounded-2xl space-y-3 shadow-2xs">
          <div className="flex items-center justify-between border-b border-slate-100 pb-2">
            <div>
              <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider flex items-center gap-1.5">
                <UserCheck className="w-4 h-4 text-blue-600" />
                <span>Phân Công Các Chức Danh Trong Lớp</span>
              </h4>
              <p className="text-[11px] text-slate-500">
                Gồm Ban cán sự lớp, Ban chấp hành Chi đoàn/Chi đội và 4 Tổ trưởng.
              </p>
            </div>
            <button
              type="button"
              onClick={handleAddCadreRow}
              className="px-2.5 py-1 rounded-lg bg-blue-50 hover:bg-blue-100 text-blue-800 border border-blue-200 text-xs font-bold transition flex items-center gap-1 cursor-pointer"
            >
              <Plus className="w-3.5 h-3.5" />
              <span>Thêm chức danh</span>
            </button>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left border-collapse">
              <thead>
                <tr className="bg-slate-100 text-slate-700 font-bold border-b border-slate-200">
                  <th className="p-2.5 w-10 text-center">TT</th>
                  <th className="p-2.5 w-1/4">Chức danh</th>
                  <th className="p-2.5 w-1/4">Họ và tên</th>
                  <th className="p-2.5 w-24 text-center">Học lực</th>
                  <th className="p-2.5 w-24 text-center">Hạnh kiểm</th>
                  <th className="p-2.5">Số điện thoại</th>
                  <th className="p-2.5 w-10 text-center">Xóa</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {formData.cadres.map((cadre, idx) => (
                  <tr key={cadre.id} className="hover:bg-slate-50/80 transition">
                    <td className="p-2 text-center font-bold text-slate-400">
                      {idx + 1}
                    </td>
                    <td className="p-2">
                      <input
                        type="text"
                        value={cadre.role}
                        onChange={(e) => handleCadreChange(idx, 'role', e.target.value)}
                        placeholder="Chức danh"
                        className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white focus:border-blue-600 focus:outline-hidden font-bold text-slate-800"
                      />
                    </td>
                    <td className="p-2">
                      <input
                        type="text"
                        value={cadre.studentName}
                        onChange={(e) => handleCadreChange(idx, 'studentName', e.target.value)}
                        placeholder="Họ và tên học sinh"
                        className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white focus:border-blue-600 focus:outline-hidden font-medium text-blue-900"
                      />
                    </td>
                    <td className="p-2">
                      <select
                        value={cadre.academicPerf}
                        onChange={(e) => handleCadreChange(idx, 'academicPerf', e.target.value)}
                        className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white"
                      >
                        <option value="Tốt">Tốt (Giỏi)</option>
                        <option value="Khá">Khá</option>
                        <option value="Đạt">Đạt (TB)</option>
                        <option value="Chưa đạt">Chưa đạt</option>
                      </select>
                    </td>
                    <td className="p-2">
                      <select
                        value={cadre.conductPerf}
                        onChange={(e) => handleCadreChange(idx, 'conductPerf', e.target.value)}
                        className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white"
                      >
                        <option value="Tốt">Tốt</option>
                        <option value="Khá">Khá</option>
                        <option value="Đạt">Đạt</option>
                      </select>
                    </td>
                    <td className="p-2">
                      <input
                        type="text"
                        value={cadre.phone}
                        onChange={(e) => handleCadreChange(idx, 'phone', e.target.value)}
                        placeholder="09..."
                        className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white focus:border-blue-600 focus:outline-hidden font-mono"
                      />
                    </td>
                    <td className="p-2 text-center">
                      <button
                        type="button"
                        onClick={() => handleRemoveCadreRow(idx)}
                        className="p-1 rounded text-slate-300 hover:text-rose-600 hover:bg-rose-50 transition cursor-pointer"
                        title="Xóa chức danh này"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* SECTION IV: DANH SÁCH HỌC SINH VẮNG */}
      {activeSection === 'absent' && (
        <div className="p-4 bg-white border border-slate-200 rounded-2xl space-y-3 shadow-2xs">
          <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 pb-2">
            <div>
              <h4 className="text-xs font-bold text-rose-900 uppercase tracking-wider flex items-center gap-1.5">
                <UserX className="w-4 h-4 text-rose-600" />
                <span>Danh Sách Học Sinh Vắng Đầu Năm Học {formData.academicYear} Của Lớp {formData.className}</span>
              </h4>
              <p className="text-[11px] text-slate-500">
                Ghi nhận đầy đủ nơi ở chi tiết, số điện thoại liên lạc và lý do chưa ra lớp để nhà trường báo cáo Sở GDĐT.
              </p>
            </div>

            <div className="flex items-center gap-2">
              {formData.absentStudents.length > 0 && (
                <button
                  type="button"
                  onClick={() => exportAbsentStudentsToExcel(formData.absentStudents, formData.className, formData.teacherName, formData.academicYear)}
                  className="px-2.5 py-1 rounded-lg bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border border-emerald-300 text-xs font-bold transition flex items-center gap-1 cursor-pointer"
                  title="Xuất bảng Excel danh sách học sinh vắng"
                >
                  <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-600" />
                  <span>Xuất Excel DS Vắng</span>
                </button>
              )}

              <button
                type="button"
                onClick={handleAddAbsentRow}
                className="px-3 py-1.5 rounded-lg bg-rose-600 hover:bg-rose-700 text-white text-xs font-bold transition flex items-center gap-1 cursor-pointer shadow-2xs"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>+ Thêm học sinh vắng</span>
              </button>

              <button
                type="button"
                onClick={handleClearAbsents}
                className="px-2.5 py-1.5 rounded-lg bg-slate-100 hover:bg-emerald-100 text-slate-700 hover:text-emerald-800 text-xs font-semibold transition cursor-pointer"
                title="Đánh dấu lớp đi đủ 100%"
              >
                <span>Lớp đi đủ 100%</span>
              </button>
            </div>
          </div>

          {formData.absentStudents.length === 0 ? (
            <div className="p-8 text-center bg-emerald-50/60 border border-emerald-200 rounded-xl space-y-2">
              <CheckCircle2 className="w-10 h-10 text-emerald-600 mx-auto" />
              <div className="text-sm font-bold text-emerald-950">
                Tuyệt vời! Lớp {formData.className || '...'} tập trung 100% học sinh (Không có học sinh vắng).
              </div>
              <p className="text-xs text-emerald-800">
                Nếu có học sinh vắng mặt, bấm nút <strong>"+ Thêm học sinh vắng"</strong> ở góc trên để ghi nhận thông tin nơi ở và số điện thoại liên lạc.
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-xs text-left border-collapse">
                <thead>
                  <tr className="bg-rose-50 text-rose-950 font-bold border-b border-rose-200">
                    <th className="p-2.5 w-10 text-center">TT</th>
                    <th className="p-2.5 w-1/5">Họ và tên học sinh</th>
                    <th className="p-2.5 w-20 text-center">Lớp cũ</th>
                    <th className="p-2.5 w-1/4">Nơi ở hiện nay (ghi rõ đường, ấp, gần chỗ nào dễ nhận dạng)</th>
                    <th className="p-2.5 w-28">SĐT HS</th>
                    <th className="p-2.5 w-28">SĐT Phụ huynh</th>
                    <th className="p-2.5">Lý do chưa ra lớp (nếu biết)</th>
                    <th className="p-2.5 w-10 text-center">Xóa</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {formData.absentStudents.map((absent, idx) => (
                    <tr key={absent.id} className="hover:bg-rose-50/30 transition">
                      <td className="p-2 text-center font-bold text-rose-600">
                        {idx + 1}
                      </td>
                      <td className="p-2">
                        <input
                          type="text"
                          value={absent.studentName}
                          onChange={(e) => handleAbsentChange(idx, 'studentName', e.target.value)}
                          placeholder="Họ và tên học sinh"
                          className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white focus:border-rose-500 focus:outline-hidden font-bold text-slate-900"
                        />
                      </td>
                      <td className="p-2">
                        <input
                          type="text"
                          value={absent.previousClass}
                          onChange={(e) => handleAbsentChange(idx, 'previousClass', e.target.value)}
                          placeholder="11CB1..."
                          className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white text-center"
                        />
                      </td>
                      <td className="p-2">
                        <textarea
                          rows={2}
                          value={absent.currentAddress}
                          onChange={(e) => handleAbsentChange(idx, 'currentAddress', e.target.value)}
                          placeholder="Số nhà, ấp, xã, gần cầu, trường học, trạm y tế..."
                          className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white focus:border-rose-500 focus:outline-hidden"
                        />
                      </td>
                      <td className="p-2">
                        <input
                          type="text"
                          value={absent.studentPhone}
                          onChange={(e) => handleAbsentChange(idx, 'studentPhone', e.target.value)}
                          placeholder="09..."
                          className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white font-mono"
                        />
                      </td>
                      <td className="p-2">
                        <input
                          type="text"
                          value={absent.parentPhone}
                          onChange={(e) => handleAbsentChange(idx, 'parentPhone', e.target.value)}
                          placeholder="09..."
                          className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white font-mono font-bold text-slate-800"
                        />
                      </td>
                      <td className="p-2">
                        <input
                          type="text"
                          value={absent.reason}
                          onChange={(e) => handleAbsentChange(idx, 'reason', e.target.value)}
                          placeholder="Gia đình đi làm xa / Nghỉ ốm / Khó khăn..."
                          className="w-full text-xs p-1.5 rounded-lg bg-slate-50 border border-slate-200 focus:bg-white focus:border-rose-500 focus:outline-hidden text-rose-900"
                        />
                      </td>
                      <td className="p-2 text-center">
                        <button
                          type="button"
                          onClick={() => handleRemoveAbsentRow(idx)}
                          className="p-1 rounded text-slate-300 hover:text-rose-600 hover:bg-rose-50 transition cursor-pointer"
                          title="Xóa học sinh này"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {/* SECTION V: XEM TRƯỚC BIÊN BẢN (PREVIEW) */}
      {activeSection === 'preview' && (
        <div className="p-6 bg-white border border-slate-200 rounded-2xl space-y-6 shadow-2xs font-serif text-slate-900">
          <div className="flex items-center justify-between border-b border-slate-200 pb-3 not-italic">
            <span className="text-xs font-sans font-bold text-slate-500 uppercase tracking-wider">
              Bản xem trước mẫu in chính thức
            </span>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => exportHomeroomReportToWord(formData)}
                className="px-3 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-sans text-xs font-bold flex items-center gap-1.5 transition cursor-pointer shadow-2xs"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Tải File Word (.doc)</span>
              </button>
            </div>
          </div>

          {/* Administrative Letterhead */}
          <div className="grid grid-cols-2 text-center text-xs leading-relaxed">
            <div>
              <div className="font-sans">SỞ GDĐT TỈNH ĐỒNG THÁP</div>
              <div className="font-sans font-bold">TRƯỜNG THCS-THPT ĐỐC BINH KIỀU</div>
              <div className="text-[10px]">***</div>
            </div>
            <div>
              <div className="font-sans font-bold">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</div>
              <div className="font-sans font-bold underline">Độc lập - Tự do - Hạnh phúc</div>
              <div className="font-sans italic text-[11px] mt-1">
                Đốc Binh Kiều, ngày {formData.meetingDate} tháng {formData.meetingMonth} năm {formData.meetingYear}
              </div>
            </div>
          </div>

          <div className="text-center my-4">
            <h3 className="text-base sm:text-lg font-bold uppercase tracking-wider">
              BIÊN BẢN
            </h3>
            <p className="text-sm font-bold">
              TẬP TRUNG HỌC SINH ĐẦU NĂM HỌC {formData.academicYear}
            </p>
          </div>

          <div className="space-y-1.5 text-xs sm:text-sm font-sans leading-relaxed text-slate-800">
            <p>
              Vào lúc <strong>{formData.timeHour}</strong> giờ <strong>{formData.timeMinute}</strong> phút, Ngày <strong>{formData.meetingDate}</strong> tháng <strong>{formData.meetingMonth}</strong> năm <strong>{formData.meetingYear}</strong>.
            </p>
            <p>
              Địa điểm: <strong>{formData.roomNumber}</strong> trường THCS-THPT Đốc Binh Kiều.
            </p>
            <p>- Họ tên GVCN: <strong>{formData.teacherName}</strong></p>
            <p>- Lớp: <strong>{formData.className}</strong></p>
            <p>
              - Số lượng học sinh của lớp: <strong>{formData.totalStudents}</strong>, trong đó nam: <strong>{formData.maleStudents}</strong>; nữ: <strong>{formData.femaleStudents}</strong>
            </p>
            <p>
              + Số học sinh vắng: <strong className="text-rose-700">{formData.absentStudents.length}</strong> (có mẫu riêng kèm theo).
            </p>
            <p className="italic text-xs text-slate-500">
              * GVCN gửi danh sách học sinh vắng SAU KHI KẾT THÚC BUỔI TẬP TRUNG HỌC SINH ĐẦU NĂM.
            </p>
          </div>

          {/* Preview Table 1 */}
          <div className="space-y-2">
            <div className="font-sans font-bold text-xs uppercase text-slate-800">
              1. Tìm hiểu về năng khiếu, thành tích của học sinh:
            </div>
            <table className="w-full text-xs border border-slate-400 border-collapse font-sans">
              <thead>
                <tr className="bg-slate-100">
                  <th className="border border-slate-400 p-2 w-10 text-center">TT</th>
                  <th className="border border-slate-400 p-2">Cuộc thi</th>
                  <th className="border border-slate-400 p-2 w-1/4 text-center">Đạt giải</th>
                  <th className="border border-slate-400 p-2 w-1/3">Họ tên học sinh đạt giải</th>
                </tr>
              </thead>
              <tbody>
                {formData.talents.map((t, idx) => (
                  <tr key={t.id}>
                    <td className="border border-slate-400 p-1.5 text-center">{idx + 1}</td>
                    <td className="border border-slate-400 p-1.5">{t.competition}</td>
                    <td className="border border-slate-400 p-1.5 text-center">{t.prize || '-'}</td>
                    <td className="border border-slate-400 p-1.5">{t.studentName || '-'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Preview Table 2 */}
          <div className="space-y-2">
            <div className="font-sans font-bold text-xs uppercase text-slate-800">
              2. Phân công các chức danh trong lớp:
            </div>
            <table className="w-full text-xs border border-slate-400 border-collapse font-sans">
              <thead>
                <tr className="bg-slate-100">
                  <th className="border border-slate-400 p-2 w-10 text-center">TT</th>
                  <th className="border border-slate-400 p-2">Chức danh</th>
                  <th className="border border-slate-400 p-2">Họ và tên</th>
                  <th className="border border-slate-400 p-2 w-20 text-center">Học lực</th>
                  <th className="border border-slate-400 p-2 w-20 text-center">Hạnh kiểm</th>
                  <th className="border border-slate-400 p-2 w-28 text-center">Số điện thoại</th>
                </tr>
              </thead>
              <tbody>
                {formData.cadres.map((c, idx) => (
                  <tr key={c.id}>
                    <td className="border border-slate-400 p-1.5 text-center">{idx + 1}</td>
                    <td className="border border-slate-400 p-1.5 font-semibold">{c.role}</td>
                    <td className="border border-slate-400 p-1.5">{c.studentName || '-'}</td>
                    <td className="border border-slate-400 p-1.5 text-center">{c.academicPerf || '-'}</td>
                    <td className="border border-slate-400 p-1.5 text-center">{c.conductPerf || '-'}</td>
                    <td className="border border-slate-400 p-1.5 text-center">{c.phone || '-'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Preview Table 3: Absent Students */}
          <div className="space-y-2">
            <div className="text-center font-bold text-xs uppercase font-sans mt-4 text-slate-900">
              DANH SÁCH HỌC SINH VẮNG ĐẦU NĂM HỌC {formData.academicYear} CỦA LỚP: {formData.className}
            </div>
            <table className="w-full text-xs border border-slate-400 border-collapse font-sans">
              <thead>
                <tr className="bg-slate-100">
                  <th className="border border-slate-400 p-2 w-8 text-center">TT</th>
                  <th className="border border-slate-400 p-2">Họ và tên học sinh</th>
                  <th className="border border-slate-400 p-2 w-20 text-center">Lớp cũ</th>
                  <th className="border border-slate-400 p-2 w-1/3">Nơi ở hiện nay</th>
                  <th className="border border-slate-400 p-2 w-24 text-center">SĐT HS</th>
                  <th className="border border-slate-400 p-2 w-24 text-center">SĐT PH</th>
                  <th className="border border-slate-400 p-2">Lý do chưa ra lớp</th>
                </tr>
              </thead>
              <tbody>
                {formData.absentStudents.length > 0 ? (
                  formData.absentStudents.map((s, idx) => (
                    <tr key={s.id}>
                      <td className="border border-slate-400 p-1.5 text-center">{idx + 1}</td>
                      <td className="border border-slate-400 p-1.5 font-medium">{s.studentName}</td>
                      <td className="border border-slate-400 p-1.5 text-center">{s.previousClass || '-'}</td>
                      <td className="border border-slate-400 p-1.5">{s.currentAddress || '-'}</td>
                      <td className="border border-slate-400 p-1.5 text-center">{s.studentPhone || '-'}</td>
                      <td className="border border-slate-400 p-1.5 text-center">{s.parentPhone || '-'}</td>
                      <td className="border border-slate-400 p-1.5">{s.reason || '-'}</td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan={7} className="border border-slate-400 p-3 text-center italic text-emerald-700">
                      Lớp tập trung đầy đủ 100% (Không có học sinh vắng)
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="grid grid-cols-2 text-center text-xs font-sans mt-8 pt-4">
            <div></div>
            <div>
              <div className="font-bold">GIÁO VIÊN CHỦ NHIỆM</div>
              <div className="italic text-[11px] text-slate-500">(Ký và ghi rõ họ tên)</div>
              <div className="h-16"></div>
              <div className="font-bold text-slate-900">{formData.teacherName}</div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
